config = {
    a_players_under_1 = { -- This will by checked first and trigger if the playercount on the server is below 1
        VehicleDensityMultiplier = 0, -- 0.00 - 1.00
        ParkedVehicleDensityMultiplier = 0, -- 0.00 - 1.00
        PedDensityMultiplier = 0, -- 0.00 - 1.00
        ScenarioPedDensityMultiplier = 0, -- 0.00 - 1.00
        DisabledDispatchServices = { -- Which dispatch services to disable
            PoliceAutomobile = true,
            PoliceAutomobileWaitPulledOver = true,
            PoliceAutomobileWaitCruising = true,
            PoliceRoadBlock = true,
            PoliceRiders = true,
            PoliceVehicleRequest = true,
            PoliceHelicopter = true,
            PoliceBoat = true,
            SwatAutomobile = true,
            SwatHelicopter = true,
            ArmyVehicle = true,
            FireDepartment = true,
            AmbulanceDepartment = true,
            Gangs = true,
            BikerBackup = true
        },
        DisableCops = true -- Wether cops will chase the player or not
    },
    b_players_under_2 = {
        VehicleDensityMultiplier = .25,
        ParkedVehicleDensityMultiplier = .75,
        PedDensityMultiplier = 1,
        ScenarioPedDensityMultiplier = 1,
        DisabledDispatchServices = {
            PoliceAutomobile = false,
            PoliceAutomobileWaitPulledOver = false,
            PoliceAutomobileWaitCruising = false,
            PoliceRoadBlock = false,
            PoliceRiders = false,
            PoliceVehicleRequest = false,
            PoliceHelicopter = false,
            PoliceBoat = false,
            SwatAutomobile = false,
            SwatHelicopter = false,
            ArmyVehicle = true,
            FireDepartment = false,
            AmbulanceDepartment = false,
            Gangs = true,
            BikerBackup = true
        },
        DisableCops = false
    },
    c_percent_under_20 = {
        VehicleDensityMultiplier = 0,
        ParkedVehicleDensityMultiplier = 0,
        PedDensityMultiplier = .8,
        ScenarioPedDensityMultiplier = 0,
        DisabledDispatchServices = {
            PoliceAutomobile = true,
            PoliceAutomobileWaitPulledOver = true,
            PoliceAutomobileWaitCruising = true,
            PoliceRoadBlock = true,
            PoliceRiders = true,
            PoliceVehicleRequest = true,
            PoliceHelicopter = true,
            PoliceBoat = true,
            SwatAutomobile = true,
            SwatHelicopter = true,
            ArmyVehicle = true,
            FireDepartment = true,
            AmbulanceDepartment = true,
            Gangs = true,
            BikerBackup = true
        },
        DisableCops = true
    },
    d_percent_under_40 = {
        VehicleDensityMultiplier = 0,
        ParkedVehicleDensityMultiplier = 0,
        PedDensityMultiplier = .4,
        ScenarioPedDensityMultiplier = 0,
        DisabledDispatchServices = {
            PoliceAutomobile = true,
            PoliceAutomobileWaitPulledOver = true,
            PoliceAutomobileWaitCruising = true,
            PoliceRoadBlock = true,
            PoliceRiders = true,
            PoliceVehicleRequest = true,
            PoliceHelicopter = true,
            PoliceBoat = true,
            SwatAutomobile = true,
            SwatHelicopter = true,
            ArmyVehicle = true,
            FireDepartment = true,
            AmbulanceDepartment = true,
            Gangs = true,
            BikerBackup = true
        },
        DisableCops = true
    },
    e_percent_over_50 = {
        VehicleDensityMultiplier = 0,
        ParkedVehicleDensityMultiplier = 0,
        PedDensityMultiplier = 0,
        ScenarioPedDensityMultiplier = 0,
        DisabledDispatchServices = {
            PoliceAutomobile = true,
            PoliceAutomobileWaitPulledOver = true,
            PoliceAutomobileWaitCruising = true,
            PoliceRoadBlock = true,
            PoliceRiders = true,
            PoliceVehicleRequest = true,
            PoliceHelicopter = true,
            PoliceBoat = true,
            SwatAutomobile = true,
            SwatHelicopter = true,
            ArmyVehicle = true,
            FireDepartment = true,
            AmbulanceDepartment = true,
            Gangs = true,
            BikerBackup = true
        },
        DisableCops = true
    }
}